### ISSUE TITLE
Releases keep failing

### ISSUE THREAD

**Issue by BYK** [getsentry/develop#579] opened 2022-05-16 09:32 UTC
Hi,

I've been getting lightly spammed by these failures for quite a while now: https://github.com/getsentry/develop/runs/6442571103?check_suite_focus=true

Would be great to fix whatever is broken and even better, find a way for them to not mention me? 😁 

/cc @chadwhitacre

**Comment by chadwhitacre** [comment] 2022-05-16 21:37
https://github.com/getsentry/develop/pull/581 should stop the spam for you @BYK, investigating root cause ...

**Comment by chadwhitacre** [comment] 2022-05-16 21:40
https://stackoverflow.com/questions/6445148/git-fatalno-tags-can-describe-sha1-number

Oh! Is this related to https://github.com/getsentry/craft/pull/343? Were we using annotated tags prior? Why doesn't this fail _everywhere_, then? Why only in this repo? I just a bunch of prepare release actions work yesterday/today with the self-hosted release. 🤔

**Comment by chadwhitacre** [comment] 2022-05-16 21:43
https://github.com/getsentry/craft/pull/343 landed ~3 months ago and failures go back ~9 months, though logs are lost past 2 months.

**Comment by chadwhitacre** [comment] 2022-05-16 21:58
I have a local repro with latest craft. I think this is going to end up as an issue over there ...

```
$ craft prepare 10.0.0 --dry-run
ℹ Checking the local repository status...                                                17:57:55
ℹ Releasing version 10.0.0 from master                                                   17:57:55
ℹ Preparing to release the version: 10.0.0                                               17:57:55
ℹ [dry-run] Not creating a new release branch                                            17:57:55

 ERROR  fatal: No tags can describe '6d54d6a413b7f9aefa5812d0501de7da353885e1'.          17:57:55
Try --always, or create some tags.


  Try --always, or create some tags.
  
  at Object.action (/Users/chadwhitacre/workbench/getsentry/craft/dist/craft:625:9722)
  at cZe.exec (/Users/chadwhitacre/workbench/getsentry/craft/dist/craft:625:10034)
  at /Users/chadwhitacre/workbench/getsentry/craft/dist/craft:623:6720
  at new Promise (<anonymous>)
  at r5.handleTaskData (/Users/chadwhitacre/workbench/getsentry/craft/dist/craft:623:6609)
  at r5.<anonymous> (/Users/chadwhitacre/workbench/getsentry/craft/dist/craft:623:6234)
  at Generator.next (<anonymous>)
  at a (/Users/chadwhitacre/workbench/getsentry/craft/dist/craft:620:1523)
  at processTicksAndRejections (internal/process/task_queues.js:95:5)

$
```

**Comment by chadwhitacre** [comment] 2022-05-16 22:05
Bug is in [here](https://github.com/getsentry/craft/blob/bcff91075c393577ef40c724b8ac5eb186ef224f/src/utils/git.ts#L38).

```
$ git describe --tags --abbrev=0
fatal: No tags can describe '6d54d6a413b7f9aefa5812d0501de7da353885e1'.
Try --always, or create some tags.
$
```

**Comment by chadwhitacre** [comment] 2022-05-16 22:12
Filed https://github.com/getsentry/craft/issues/395, but ...

```
$ git tag
21.9.0
```

🤔

**Comment by chadwhitacre** [comment] 2022-05-16 22:17
The [commit](https://github.com/getsentry/craft/commit/6c67e883ec9ef6e89385e03d214dfe9c3f2c995c) that 21.9.0 points to is not on any branch.

```
$ git branch --contains 6c67e883ec9ef6e89385e03d214dfe9c3f2c995c
$
```

**Comment by chadwhitacre** [comment] 2022-05-16 22:20
Looks like the release commit (carrying the tag) is expected to be on the default branch.

```
$ git describe --tags --abbrev=0
22.5.0
$ git branch --contains de07b479af8834d7e5d629cb152cf45ac6f02ba5
* master
$
```

**Comment by chadwhitacre** [comment] 2022-05-16 22:29
https://github.com/getsentry/develop/pull/581 merged so light spam should stop @BYK. 🙏

**Comment by chadwhitacre** [comment] 2022-05-16 22:31
Well this doesn't look good:

```
* commit 45cd9b19374b403ba8c6c210e21dbe26b3faf263
| Author: Chad Whitacre <chadwhitacre@sentry.io>
| Date:   Wed Sep 15 16:23:41 2021 -0400
| 
|     release: 21.9.0 (#434)
|     
|     Co-authored-by: getsentry-bot <bot@sentry.io>
| 
* commit dcc5a06da56c35611864f33ee60e7dd433f7372f
| Author: Kamil Ogórek <kamil.ogorek@gmail.com>
| Date:   Wed Sep 15 20:35:13 2021 +0200
| 
|     docs(envelopes): Update envelope header requirement (#433)
|     
|     * docs(envelopes): Update envelope header requirement
|     
|     * add a note regarding envelope header being required
|     * remove an example without envelope header
|     * fix title of one of the examples
|     
|     * Update src/docs/sdk/envelopes.mdx
|   
| * commit 6c67e883ec9ef6e89385e03d214dfe9c3f2c995c (tag: 21.9.0)
|/  Author: getsentry-bot <bot@sentry.io>
|   Date:   Wed Sep 15 18:02:30 2021 +0000
|   
|       release: 21.9.0
| 
* commit afb3e766967813ca586d85ada5c30c858ef6dc41
```

**Comment by chadwhitacre** [comment] 2022-05-16 22:32
https://github.com/getsentry/publish/issues/544

**Comment by chadwhitacre** [comment] 2022-05-16 22:32
> Finished this manually.

https://github.com/getsentry/publish/issues/544#issuecomment-920411562

**Comment by chadwhitacre** [comment] 2022-05-16 22:33
> Error: The log was not found. It may have been deleted based on retention settings.

https://github.com/getsentry/publish/runs/3613388872?check_suite_focus=true

😞

**Comment by chadwhitacre** [comment] 2022-05-16 22:38
Alright, so it looks like we got bit by a race condition during 21.9.0 and @kamilogorek snuck in a commit between the bot's attempt and my attempt to release 21.9.0. Since this is just a docs repo and is low-risk and this is hardly a big deal (right? right!?), my plan is to retag 21.9.0 to 45cd9b19374b403ba8c6c210e21dbe26b3faf263, and then retry a new release.

**Comment by chadwhitacre** [comment] 2022-05-16 22:42
Old commit is 6c67e883ec9ef6e89385e03d214dfe9c3f2c995c for the record, renamed tag to `21.9.0-old` (still linked to GitHub's [release record](https://github.com/getsentry/develop/releases/tag/21.9.0-old), added a note). `21.9.0` now points to 45cd9b19374b403ba8c6c210e21dbe26b3faf263. New release run: https://github.com/getsentry/develop/actions/runs/2335084422 => https://github.com/getsentry/publish/issues/1092.

**Comment by chadwhitacre** [comment] 2022-05-16 22:45
A'ight, calling this [good](https://github.com/getsentry/develop/releases/tag/22.5.0). ✌️

**Closed by chadwhitacre** 2022-05-16 22:45 UTC
