### ISSUE TITLE
Document missing fields from span interface

### ISSUE THREAD

**Issue by marandaneto** [getsentry/develop#318] opened 2021-04-28 08:28 UTC
The docs on spans don't cover the span_id/parent_span_id/sampled fields and potentially some others. What is the list of fields required/allowed on spans?

https://develop.sentry.dev/sdk/event-payloads/span/

Source https://github.com/getsentry/develop/issues/221

**Comment by rhcarvalho** [comment] 2021-05-07 08:30
This is a rendering bug, see #170.

The source code has the includes for `span_id` and `parent_span_id`:

![image](https://user-images.githubusercontent.com/88819/117421528-e6250e80-af1e-11eb-8a5b-c9fd750bb09a.png)


Note that `sampled` is not part of the spec intentionally, otherwise it would be a field that would be always `true`, because `sampled: false` means do not send it.
Therefore, `sampled` is an internal field that tracks the in-memory state of the span, but is not part of its JSON serialization when sending to Sentry.

Closing this as a duplicate of #170, since this will be fixed once we fix that one.

**Closed by rhcarvalho** 2021-05-07 08:30 UTC
Labels: performance
