### ISSUE TITLE
Simplify Turning Performance on in SDK Config

### ISSUE THREAD

**Issue by smeubank** [getsentry/develop#769] opened 2022-11-23 11:33 UTC
### Background
When Performance was first added to Sentry there were options added to SDKs to turn on and then set the sample rate. The sample rate config is included in code snippets to simplify the copy paste and turning on of Sentry's performance and tracing products.

Since Performance has been live for a while now it would make sense that it is treated in SDKs the same as it is treated in our product experience. Which is that it is included by default in your quota and UI

### Proposal
[SDK Configuration](https://develop.sentry.dev/sdk/performance/#sdk-configuration) should change such that 

> Tracing is enabled by setting either one of two new SDK config options, tracesSampleRate and tracesSampler. If not set, both default to undefined, making tracing opt-in.

becomes

> Tracing is enabled by default. To change the sampling rate and functionality `tracesSampleRate` and `tracesSampler`are available. If set to `0.0` transactions and traces will not be generatedTracing is enabled by setting either one of two new SDK config options, `tracesSampleRate` and `tracesSampler`. If not set, the `tracesSampleRate` defaults to `1.0`, making tracing by default on.

### Considerations
- This could be a breaking change and would require major releases per SDK
- should consider the default value to not be 1.0 for platforms where it makes sense

### To dos:
Update dev docs
Update SDK docs
- landing pages 
- onboarding wizard(s) in product
Update cli wizard
Update SDKs
- major releases

**Comment by smeubank** [comment] 2022-11-23 11:35
for JS we must consider that tracing is imported on it's own

but with V8 we are discussing changes where tracing and session replay would not need to be imported separately, and users to remove the code if they want with tree shaking functionality

**Comment by cleptric** [comment] 2022-11-23 11:39
> If not set, both default to 1.0, making tracing by default on.

It should suffice to set either of these, so defaulting `tracesSampleRate: 1.0` is enough.

We could also debate if this is a BC-breaking change, as it won't break people's code, but rather change the default behavior of the SDK.

**Comment by smeubank** [comment] 2022-11-23 12:44
> It should suffice to set either of these, so defaulting tracesSampleRate: 1.0 is enough.
updated description

> We could also debate if this is a BC-breaking change, as it won't break people's code, but rather change the default behavior of the SDK.
agreed i changed the original description from would to could for just that reason :D

> We should also look into how the product behaves with this change. Will people without any txn quota get spammed with emails?
great point! @rahulchhabria would you have any thoughts here? Most all orgs should have some txn quota today. But are there any consideration we should put into the to-do for CTAs in product or emails?

**Comment by smeubank** [comment] 2022-11-23 16:08
- ops infra concern: bumps incoming traffic
- legal/PII: folks would start sending traces and span data to sentry including data which they may not want to send or know they are sending
- SDKs: consider down stream sampling and tracing decisions

**Comment by dcramer** [comment] 2022-11-23 16:48
Whats the motiviation for this change? Feel like there's a lot of low hanging fruit we should tackle instead of messing w/ tracing config which will 100% create more "i didnt realize perf was enabled" tickets, let alone problems for self-hosted users.

**Comment by dcramer** [comment] 2022-11-23 17:18
Decision: keep it obvious that performance is on in the same way we do it today. We don't want to accidentally trick customers or create more confusion, and performance is not used by everyone (and costs money).

**Comment by ndmanvar** [comment] 2022-11-23 18:33
what if `BrowserTracing`integration is installed, then `tracesSampleRate` isn't mandatory and will default to 1.0?

i.e.
```
import * as Sentry from "@sentry/browser";
import { BrowserTracing } from "@sentry/tracing";

Sentry.init({
  dsn: "https://XXXX@Y.ingest.sentry.io/PROJ_ID",

  // Alternatively, use `process.env.npm_package_version` for a dynamic release version
  // if your build tool supports it.
  release: "my-project-name@2.3.12",
  integrations: [new BrowserTracing()],

  // Don't need to specify this explicitly as `BrowserTracing` lib is imported -> **Defaulting to 1.0**
  // tracesSampleRate: 1.0,

});
```

**Comment by dcramer** [comment] 2022-11-23 18:55
`enablePerformance=true/false`

**Comment by cleptric** [comment] 2022-11-23 19:01
> enablePerformance=true/false

This behavior is achieved by `tracesSampleRate: null/nil/None…`

**Comment by danielkhan** [comment] 2022-11-23 19:07
> This behavior is achieved by tracesSampleRate: null/nil/None…

@cleptric please read [my comment](https://github.com/getsentry/develop/issues/769#issuecomment-1325430780).

There are reasons to not use `tracesSampleRate` as an implicit switch.

**Comment by cleptric** [comment] 2022-11-23 22:44
When setting `tracesSampleRate: 0.0`, transactions will still be started if the head SDK sends a `sentry-trace` header with a `-1` sampling decision.

See https://develop.sentry.dev/sdk/performance/#sampling

To allow people to completely opt out of sampling, we just introduced the new default `null` option in PHP and Laravel.

https://github.com/getsentry/sentry-php/pull/1428
https://github.com/getsentry/sentry-laravel/pull/616

This is in line with how it has been in our Ruby and Python SDKs.

**Comment by philipphofmann** [comment] 2022-11-28 15:50
Can we agree on the following?

1. Adding enablePerformance with default true
2. The default of `tracesSampleRate` is `1.0`

These changes would need to be done in a next major of the SDKs.

**Comment by rbisol** [comment] 2022-11-30 07:31
> We could also debate if this is a BC-breaking change, as it won't break people's code, but rather change the default behavior of the SDK.

This needs to be added as a breaking change. People will update the SDK and get the transaction quota blown up if it is enabled and set to 1.0 by default. I informed the engineering team about this being a problem 3 times already. Also: 

> Dynamic Sampling only applies above 5M+ transactions, but we do show the settings even for newly created orgs on AM2/Developer (aka free tier).

I don't have exact numbers, but I don't see customers with 5M+ transactions.

**Comment by philipphofmann** [comment] 2022-11-30 16:07
So the outcome is to not set `tracesSampleRate = 1.0`, not add an extra flag `tracesSampleRate`, because we don't want an extra flag. Users should copy the `tracesSampleRate = 1.0` from the docs.

**Comment by danielkhan** [comment] 2022-11-30 16:21
How as this conclusion reached?

**Comment by danielkhan** [comment] 2022-12-06 07:51
Let me resurrect this discussion and reiterate.
Why are we doing this?
As we continue moving to dynamic/biased sampling strategies, setting the client sample rate should not be the way to to switch on tracing. This is an UX improvement. 

There is no BC issue. 

This is the expected behavior:
```
tracesSampleRate = r
// Tracing on with rate r

tracesSampleRate = r
enablePerformance = true
// Tracing on with rate r

tracesSampleRate = null | undefined
enablePerformance = true
// Tracing on with rate=1.0


integrations: [new BrowserTracing()],
// Tracing on with rate=1.0

integrations: [new BrowserTracing()],
enablePerformance = true
// Tracing on with rate=1.0

integrations: [new BrowserTracing()],
enablePerformance = true
tracesSampleRate = r
// Tracing on with rate=r
```

**Comment by ndmanvar** [comment] 2022-12-16 16:44
@danielkhan - any updates/movement on this one?

**Comment by philipphofmann** [comment] 2022-12-20 09:18
> So the outcome is to not set `tracesSampleRate = 1.0`, not add an extra flag `tracesSampleRate`, because we don't want an extra flag. Users should copy the `tracesSampleRate = 1.0` from the docs.

For clarification. We never reached this conclusion. That was a miscommunication on my side. The discussion is still open.

**Comment by smeubank** [comment] 2023-01-05 08:40
> `enablePerformance=true/false`

revisiting this after the holidays, I think the most desired outcome here is this, the default will be false and code snippets in docs would include true, similar to the behavior with sample rate, 

default sample rates behind this config would be platform specific, considering overhead concerns. I will draft a develop docs PR to agree upon there

**Comment by jeremybourque** [comment] 2023-01-13 16:28
> revisiting this after the holidays, I think the most desired outcome here is this, the default will be false and code snippets in docs would include true, similar to the behavior with sample rate,

This makes the most sense to me. It works basically the same as before but asks only for a on/off decision without making people also think about what sample rate to use. The sample rate controls will still be there to support existing configs and for folks that still need SDK level sampling for whatever reason.

**Closed** 2023-02-06 13:18 UTC
Labels: enhancement, performance, Impact: Medium
